import 'package:flutter/material.dart';

final Map<String, Color> chordToColor = {
  'C':  Colors.redAccent,
  'Cm': Colors.redAccent,
  'C#': const Color(0xFFFF6600),
  'C#m': const Color(0xFFCC5200),
  'D': const Color(0xFFFFCC00),
  'Dm': const Color(0xFFCCA300),
  'D#': Colors.blueGrey,
  'D#m': const Color(0xFF7ACC00),
  'E': Colors.teal,
  'Em': Colors.pink,
  'F': Colors.orangeAccent,
  'Fm': Colors.deepPurpleAccent,
  'F#': Colors.brown,
  'F#m': const Color(0xFF00CCCC),
  'G': const Color(0xFF0099FF),
  'Gm': const Color(0xFF007ACC),
  'G#': const Color(0xFF0000FF),
  'G#m': const Color(0xFF0000CC),
  'A': const Color(0xFF9900FF),
  'Am': const Color(0xFF7A00CC),
  'A#': const Color(0xFFFF00FF),
  'A#m': const Color(0xFFCC00CC),
  'B': const Color(0xFFFF0099),
  'Bm': const Color(0xFFCC007A),
};
